### ISSUE TITLE
[RESOLVED] Kernel source not updated

### ISSUE THREAD

**Issue by ghost** [OnePlusOSS/android_kernel_oneplus_msm8994#13]
Please release the kernel source for oos 3.6.0

**Comment by xdevs23** [comment]
Soon™

**Comment by aaronqiuchiu** [comment]
@anupritaisno1 please get the kernel source from below URL
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8994/tree/oneplus/6.0.1

**Comment by xdevs23** [comment]
You guys using Internet Explorer?

**Comment by aaronqiuchiu** [comment]
@xdevs23 ssh ways
git@github.com:OnePlusOSS/android_kernel_oneplus_msm8994.git

**Comment by xdevs23** [comment]
Lol wtf

**Comment by regalstreak** [comment]
They really do use Internet Explorer that too with wine

**Comment by xdevs23** [comment]
Would be better if they switch to Netscape Navigator

**Comment by jisakiel** [comment]
@aaronqiuchiu last commit is https://github.com/OnePlusOSS/android_kernel_oneplus_msm8994/commit/c0ed8f21707f9712bdee986274b9361515b965ef which is only for OOS 3.5.8. 

The GPLv2 under which the kernel is licensed legally obliges you to release the kernel source for OOS 3.6.0, in case there has been any modifications since then.

**Comment by shivsah** [comment]
@aaronqiuchiu please update kernel for Oxygen OS 3.6.1

**Comment by aaronqiuchiu** [comment]
@shivsah  kernel no changed on Oxygen OS 3.6.1

**Comment by ghost** [comment]
Hi guys I just wanna clear some confusion here
First of all sorry for the late reply but I already talked with one of their representatives quite a long time ago and they haven't made any changes to the kernel so asking is useless. There have been no changes at all
They never made a change since 3.5.8

@aaronqiuchiu when people see an opportunity to fight they will do so anyways. It would be much better if this issue is totally deleted because it's not doing any good. So do everyone a favor and hit the delete button on this issue

**Comment by anupritaisno1** [comment]
I have changed the title to "resolved"
No further discussion on this guys

**Comment by xdevs23** [comment]
Nougat please xD
