### ISSUE TITLE
Compile Issue for .config and make

### ISSUE THREAD

**Issue by JengaMasterG** [OnePlusOSS/android_kernel_oneplus_msm8994#3]
When compiling .config file I see this error:
In file included from drivers/media/platform/msm/camera_v2/sensor/vl6180/inc/vl6180x_api.h:39:0,
                 from drivers/media/platform/msm/camera_v2/sensor/vl6180/stmvl6180_module.c:37:
drivers/media/platform/msm/camera_v2/sensor/vl6180/inc/vl6180x_def.h:497:0: warning: "MODE_MASK" redefined
error, forbidden warning: vl6180x_def.h:497
make[7]: **\* [drivers/media/platform/msm/camera_v2/sensor/vl6180/stmvl6180_module.o] Error 1
make[6]: **\* [drivers/media/platform/msm/camera_v2/sensor/vl6180] Error 2
make[5]: **\* [drivers/media/platform/msm/camera_v2/sensor] Error 2
make[4]: **\* [drivers/media/platform/msm/camera_v2] Error 2
make[3]: **\* [drivers/media/platform/msm] Error 2
make[2]: **\* [drivers/media/platform] Error 2
make[1]: **\* [drivers/media] Error 2
make: **\* [drivers] Error 2

it stops the compile so I don't get to continue creating the kernel

**Comment by flaviopace** [comment]
HI @ZeroX25 

Which _defconfig file are you using? and Which toolchain? I have similar issue building official kernel... but I'm not able to find any guide/tutorial how to build official Kernel

Thanks

**Comment by JengaMasterG** [comment]
I'm using the msm8974_defconfig file and I believe the androideabi 4.9 tool chain from android googlesource.

**Comment by JengaMasterG** [comment]
@AuxXxilium and @FrozenCow,

What are the references for? (I'm still new to to GitHub).

**Comment by FrozenCow** [comment]
You can refer to issues from commit messages with for instance "#3" (this
issue has id 3). The problem is that many commits that are already in the
kernel contain such texts (but are not intended to refer to issues of
github). So, when someone pushes a large number of commits there's a good
chance a 'reference' to an issue that is in there unintentionally. You can
ignore them in this repository. I'm not sure how to circumvent them.

**Comment by JengaMasterG** [comment]
Oh okay. I don't know how to solve it which is why I posted the issue.

**Comment by JengaMasterG** [comment]
Need to remove the MODE MASK change in vl6180x_def.h
