### ISSUE TITLE
Drivers/USB Compile issue

### ISSUE THREAD

**Issue by JengaMasterG** [OnePlusOSS/android_kernel_oneplus_msm8994#6]
I get this issue when trying to compile:

drivers/usb/storage/ene_ub6250.c: In function 'ene_ms_init':
drivers/usb/storage/ene_ub6250.c:2125:1: warning: the frame size of 1104 bytes is larger than 1024 bytes [-Wframe-larger-than=]

I don't know what file to change in order for this to work.

Thanks!

**Comment by JengaMasterG** [comment]
The reference doesn't help if I don't know where to fix the issue in the first place...

**Comment by regalstreak** [comment]
Never got this.. Which toolchain you using?

**Comment by JengaMasterG** [comment]
Androideabi 4.9 that supports lollipop also. I figured it could've been the toolchain, but other toolchains were giving me random errors that didn't make them work.

**Comment by JengaMasterG** [comment]
Supports marshmallow*

**Comment by JengaMasterG** [comment]
I was compiling msm8974_defconfig in the arch/arm/configs folder and not the msm8974-OnePlus2_defconfig in arch/arm64/configs so switching .configs fixed the issue.

**Comment by ghost** [comment]
I'm getting this same error, but I'm on a different device, LG G3 D850.  I'm using cyanogenmod_d850_defconfig.  Can you help?

**Comment by regalstreak** [comment]
use the correct defconfig. As said above @navenedrob
